input:
  period: 10
  procs: [".*"]
  stats:
    system: true
    process: true
    filesystem: true
    cpu_per_core: false
output:
  elasticsearch:
    hosts: ["elasticsearch:9200"]
shipper:
logging:
  files:

