---

- name: install topbeat
  yum: 
    name: https://download.elastic.co/beats/topbeat/topbeat-1.3.1-x86_64.rpm
    state: present

- name: copy topbeat yaml
  copy: src=topbeat.yml dest=/etc/topbeat owner=root group=root mode=0644 backup=yes

- name: start topbeat
  service:
    name: topbeat
    enabled: yes
    masked: no
    state: started
