filebeat.modules:
- module: system
  syslog:
    enabled: true
- module: apache2
  access:
    enabled: true
    var.paths: ["/var/log/httpd/access_log"]
  error:
    enabled: true
    var.paths: ["/var/log/httpd/error_log"]
- module: auditd
  log:
    enabled: true
- module: mysql
  error:
    enabled: true
    var.paths: ["/var/log/mariadb/mariadb.log"]
filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/*/*.log
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
dashboards.enabled: true
